# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4e99f6d544b75f99c9a3eb8eaa10dff6c6fd633546ce46ede53cbce67d3fe25de00aa2283894f0b38c772d5e7c8372af05b1bfbc1c9a1e0578c7b55de6d4276

test:
  secret_key_base: b0c050a98835901c5ad98680a3beb75c446e9b661444a0ff71a078680eeadafc3b27b92239022af6caaa49003bea8b461d3e0dd8b46eb16f3ebacadb84ab47ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
